### ISSUE TITLE
Cosmetic issues in docs

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-grpc-quickstart-scala.g8#12]
(see java counterpart https://github.com/akka/akka-grpc-quickstart-java.g8/issues/8)

When [rendered](https://developer.lightbend.com/guides/akka-grpc-quickstart-scala/) a few of snippets appear malformed.

**Comment by raboof** [comment]
Very weird, I can't reproduce this even after applying the Tech Hub Theme as per https://github.com/lightbend/techhub/blob/038ecc2a6d403f7b34f87fe58cfc70e589872528/sbt-docsites/src/main/scala/MakeSiteAction.scala#L139 (0.2.14). Could this be related to https://github.com/lightbend/techhub/issues/177?
