### ISSUE TITLE
Sample no longer works nicely in IntelliJ

### ISSUE THREAD

**Issue by johanandren** [akka/akka-grpc-quickstart-scala.g8#22]
Downloading the starter project and importing to IntelliJ does not find the generated classes (those added through the akka-grpc-plugin I think) and it is a bit tricky finding what sbt plugin flags to toggle to get the imports right. This could be an issue with some change of the plugin or the intellij sbt support, not sure.

**Comment by johanandren** [comment]
I could work around not finding the sources by manually marking `target/scala-2.12/src_managed` as generated sources.

**Comment by ignasi35** [comment]
I had to run `sbt compile` on a separate terminal but everything worked as expected for me.

1. `sbt new akka/akka-grpc-quickstart-scala.g8` (using `addSbtPlugin("com.lightbend.akka.grpc" % "sbt-akka-grpc" % "0.6.1")` already)
1. import on intelliJ
1. run `sbt compile` on a separate terminal
1. navigate to `GreeterServiceImpl` on IntelliJ (all imports and generated classes are recognised and found)
