### ISSUE TITLE
FAILED: java.lang.NoSuchMethodError: sbt.package$.singleFileJsonFormatter

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-grpc-quickstart-scala.g8#31]
Since March 19th the `CRON` build is [broken](https://travis-ci.org/github/akka/akka-grpc-quickstart-scala.g8/jobs/666907559#L435).

**Comment by ignasi35** [comment]
I tried cleaning caches in travis but didn't fix the issue.

**Comment by ignasi35** [comment]
Note that the same commit built successfully several times in `CRON`-triggered builds before is started failing: https://travis-ci.org/github/akka/akka-grpc-quickstart-scala.g8/builds

**Comment by raboof** [comment]
Interesting! It might be due to an update to one of the artifacts that auto-update without needing commits, mainly akka and akka-grpc, found at https://github.com/akka/akka-grpc-quickstart-scala.g8/blob/master/src/main/g8/default.properties .

**Comment by ignasi35** [comment]
Your'e completely right. The release of [`0.8.1`](https://github.com/akka/akka-grpc/tree/v0.8.1) broke this build:

<img width="1447" alt="Screenshot_2020-03-31_at_18_36_34" src="https://user-images.githubusercontent.com/762126/78051922-aa646080-737e-11ea-8e73-a7a3a07f3424.png">


Let's see how the `0.8.2` (just fresh out of the oven) impacts this build.
