### ISSUE TITLE
Unresolved dependency

### ISSUE THREAD

**Issue by joshuakidd** [akka/akka-grpc-quickstart-scala.g8#4]
On 'sbt run' the akka-grpc is unresolved.  

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.lightbend.akka.grpc#sbt-akka-grpc;0.1+64-3433908f: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

**Comment by ktoso** [comment]
Try plain `0.1`, there's an issue with docs publishing which adds the suffix. We're working on it.

**Comment by chbatey** [comment]
This quickstart is based on a version that isn't published. It'll be ready to use for 0.2
